from enum import StrEnum


class RegimeState(StrEnum):
    UPTREND_LOW_VOL = "UPTREND_LOW_VOL"
    UPTREND_HIGH_VOL = "UPTREND_HIGH_VOL"
    DOWNTREND_LOW_VOL = "DOWNTREND_LOW_VOL"
    DOWNTREND_HIGH_VOL = "DOWNTREND_HIGH_VOL"
    SIDEWAYS_LOW_VOL = "SIDEWAYS_LOW_VOL"
    SIDEWAYS_HIGH_VOL = "SIDEWAYS_HIGH_VOL"
    BREAKOUT_WATCH = "BREAKOUT_WATCH"
    NO_TRADE = "NO_TRADE"

